Controllers/LokacijaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using IamHungry.Models;

namespace IamHungry.Controllers
{
    public class LokacijaController : Controller
    {
        FDBContext fdb = new FDBContext();
        // GET: Lokacija
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NoviGrad()
        {
            ViewBag.zupanija = new SelectList(fdb.Zupanija, "ZupId", "ZupIme");
            return View();
        }

        [HttpPost]
        public ActionResult NoviGrad(Grad grad)
        {
            if (ModelState.IsValid)
            {
                Kvart nk = new Kvart();
                nk.PostBroj = grad.PostBroj;
                nk.ImeKvarta = grad.ImeGrada;
                nk.KvartId = "" + nk.ImeKvarta.Substring(0, 3) + "" + nk.PostBroj.ToString();
                fdb.Grad.Add(grad);
                fdb.Kvart.Add(nk);
                fdb.SaveChanges();
                return RedirectToAction("RegisterRestorana", "Account");
            }
            ViewBag.FAILGRAD = "Greska prilikom unosa novog grada!";
            return View();
        }

        public ActionResult NoviKvart()
        {
            ViewBag.gradNK = new SelectList(fdb.Grad, "PostBroj", "ImeGrada");
            return View();
        }

        [HttpPost]
        public ActionResult NoviKvart(Kvart kvart)
        {
            if (ModelState.IsValid)
            {
                kvart.KvartId = "" + kvart.ImeKvarta.Substring(0, 3) + "" + kvart.PostBroj.ToString();
                fdb.Kvart.Add(kvart);
                fdb.SaveChanges();
                return RedirectToAction("RegisterRestorana", "Account");
            }
            ViewBag.FAILKVART = "Greska prilikom unosa novog kvarta!";
            return View();
        }
    }
}

Controllers/RestoranController.cs
using IamHungry.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IamHungry.Controllers
{
    public class RestoranController : Controller
    {

        FDBContext fdb = new FDBContext();
        // GET: Restoran
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult UrediRestoran()
        {
            GradDropDownList();
            KvardDropDownList();
            return View();
        }

        [HttpPost]
        public ActionResult UrediRestoran(Restoran restoran)
        {
            if (Session["UserId"] != null)
            {
                restoran.RestId = Session["UserId"].ToString();
            }
            if (ModelState.IsValid)
            {
                Restoran r = fdb.Restoran.Find(restoran.RestId);

                r.ImeRest = restoran.ImeRest;
                if(restoran.KucniBroj != null)
                {
                    r.KucniBroj = restoran.KucniBroj;
                }
               
                r.KvartId = restoran.KvartId;
                r.PostBroj = restoran.PostBroj;

                if(restoran.Passw != null)
                {
                    r.Passw = restoran.Passw;
                }
               
                if(restoran.Ulica != null)
                {
                    r.Ulica = restoran.Ulica;
                }
                
                if(restoran.email != null)
                {
                    r.email = restoran.email;
                }
                
                if(restoran.Telefon != null)
                {
                    r.Telefon = restoran.Telefon;
                }
                
                if(restoran.Mobitel != null)
                {
                    r.Mobitel = restoran.Mobitel;
                }
               
                if(restoran.VlasnikId != null)
                {
                    r.VlasnikId = restoran.VlasnikId;
                }
                

                fdb.SaveChanges();
               
                return RedirectToAction("Index", "Home");
            }

            ViewBag.EditRestMessage = "Niste uspjeli promijeniti podatke o restoranu!"; 
            return View();
        }

        public ActionResult UrediDostavu()
        {
            string rest = Session["UserId"].ToString();
            var dost = from d in fdb.Dostava where d.RestId == rest select d;
            return View(dost);
        }

        public ActionResult IzmijeniDostavu(string idD)
        {
            Dostava d = new Dostava();
            d.DostavaId = idD;
            d.RestId = Session["UserId"].ToString();
            ViewBag.GradD = new SelectList(fdb.Grad, "PostBroj", "ImeGrada");
            ViewBag.KvartD = new SelectList(fdb.Kvart, "KvartId", "ImeKvarta");
            return View(d);
        }

        [HttpPost]
        public ActionResult IzmijeniDostavu(Dostava d)
        {
            var dost = fdb.Dostava.Find(d.DostavaId);
            if (ModelState.IsValid)
            {
                if(d.vrijeme != null)
                {
                    dost.vrijeme = d.vrijeme;
                    dost.PostBroj = d.PostBroj;
                    dost.KvartId = d.KvartId;
                }
                fdb.SaveChanges();
                return RedirectToAction("UrediDostavu");
            }
            ViewBag.FAILAZDOSTAVA = "Greska pri izmijeni dostave!";
            return View(d);
        }

        public ActionResult IzbrisiDostavu(string idD)
        {
            var d = fdb.Dostava.Find(idD);
            fdb.Dostava.Remove(d);
            fdb.SaveChanges();
            return RedirectToAction("UrediDostavu");
        }

        public ActionResult DodajDostavu()
        {
            GradDropDownList();
            KvardDropDownList();

            Dostava d = new Dostava();
            d.RestId = Session["UserId"].ToString();
            return View(d);
        }

        [HttpPost]
        public ActionResult DodajDostavu(Dostava d)
        {
            d.DostavaId = d.RestId.Substring(0, 5).ToString() + d.KvartId.Substring(0, 5).ToString();
            if (ModelState.IsValid)
            {
                fdb.Dostava.Add(d);
                fdb.SaveChanges();
                return RedirectToAction("UrediDostavu");
            }
            ViewBag.FAILDOSTAVA = "Greska pri unosu nove dostave!";
            return View(d);
        }

        public ActionResult RadnoVrijeme()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RadnoVrijeme(RadnoVrijeme rv)
        {
            if (Session["UserId"] != null)
            {
                rv.RestId = Session["UserId"].ToString();
                rv.RestRadId = rv.RestId.Substring(0, 5).ToString() + rv.dan.ToString();
            }
            if (ModelState.IsValid)
            {
                fdb.RadnoVrijeme.Add(rv);
                fdb.SaveChanges();
                ViewBag.RadnoVrijeme = "Azurirali ste radno vrijeme za " + rv.dan.ToString() + " na: " + rv.VrijemeOd.ToString() + " - " + rv.VrijemeDo.ToString();
                return View();
            }
            return View();
        }

        private void GradDropDownList(object selectedGrad = null)
        {
            ViewBag.Grad2 = new SelectList(fdb.Grad, "PostBroj", "ImeGrada", selectedGrad);
        }
        private void KvardDropDownList(object selectedKvart = null)
        {
            ViewBag.Kvart = new SelectList(fdb.Kvart, "KvartId", "ImeKvarta", selectedKvart);
        }
    }
}

Views/Restoran/DodajDostavu.cshtml
@model IamHungry.Models.Dostava
<br><br><br>
<h3>Dostava</h3>
<hr />

@if(ViewBag.FAILDOSTAVA != null)
{
    <h4>
        @ViewBag.FAILDOSTAVA
    </h4>
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RestId)
     

        <div class="form-group">
            @Html.LabelFor(model => model.KvartId, "Kvart", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KvartId", (SelectList)ViewBag.Kvart, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KvartId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostBroj, "Grad", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PostBroj", (SelectList)ViewBag.Grad2, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PostBroj, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vrijeme, "Vrijeme", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vrijeme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vrijeme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak", "UrediDostavu")|
    @Html.ActionLink("Novi Kvart", "NoviKvart", "Lokacija")
</div>

Views/Restoran/IzmijeniDostavu.cshtml
@model IamHungry.Models.Dostava
<br><br><br>
<h4>Dostava</h4>
<hr />

@if(ViewBag.FAILAZDOSTAVA != null)
{
    <h4>
        @ViewBag.FAILAZDOSTAVA
    </h4>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RestId)
        @Html.HiddenFor(model => model.DostavaId)


        <div class="form-group">
            @Html.LabelFor(model => model.PostBroj, "Grad", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PostBroj", (SelectList)ViewBag.GradD, htmlAttributes: new { @class = "form-control" } )
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KvartId, "Kvart", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KvartId", (SelectList)ViewBag.KvartD, htmlAttributes: new { @class = "form-control" } )
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vrijeme, "Vrijeme", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vrijeme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vrijeme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Izmijeni" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak", "UrediDostavu")
</div>

Views/Restoran/RadnoVrijeme.cshtml
@model IamHungry.Models.RadnoVrijeme
<br><br><br>
@if(ViewBag.RadnoVrijeme != null)
{
    <h2>
        @ViewBag.RadnoVrijeme
    </h2>
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h2>Radno Vrijeme</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.dan, "Dan", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VrijemeOd, "Vrijeme od", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VrijemeOd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VrijemeOd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VrijemeDo, "Vrijeme do", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VrijemeDo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VrijemeDo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusRada, "Status rada", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    List<SelectListItem> listItems2 = new List<SelectListItem>();
                    listItems2.Add(new SelectListItem
                    {
                        Text = "Radimo",
                        Value = "Radimo",
                        Selected = true
                    });
                    listItems2.Add(new SelectListItem
                    {
                        Text = "Ne radimo",
                        Value = "Ne radimo"
                    });
                  
                }

                @Html.DropDownListFor(model => model.StatusRada, listItems2, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusRada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Azuriraj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak na uredivanje", "Uredivanje", "Home")
</div>

Views/Restoran/UrediDostavu.cshtml
@model IEnumerable<IamHungry.Models.Dostava>
<br><br><br>
<h3>
    @Session["UserName"]
</h3>
<br>
<p>
    @Html.ActionLink("Dodaj kvart dostave", "DodajDostavu")
</p>
<br>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Grad")
        </th>
        <th>
            @Html.DisplayName("Kvart")
        </th>
        <th>
            @Html.DisplayName("Vrijeme")
        </th>


        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Grad.ImeGrada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Kvart.ImeKvarta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.vrijeme)
        </td>


        <td>
            @Html.ActionLink("Izmijeni", "IzmijeniDostavu", new { idD = item.DostavaId }) |
            @Html.ActionLink("Izbrisi", "IzbrisiDostavu", new { idD = item.DostavaId })
        </td>
    </tr>
}

</table>

Views/Restoran/UrediRestoran.cshtml
@model IamHungry.Models.Restoran
<br><br><br>
@{
    ViewBag.Title = "UrediRestoran";
}

<h2>Uredi restoran</h2>

@if(ViewBag.EditRestMessage != null)
{
    <h4>
        @ViewBag.EditRestMessage
    </h4>
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.ImeRest, "Ime restorana", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImeRest, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImeRest, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostBroj, "Grad", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PostBroj", (SelectList)ViewBag.Grad2, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PostBroj, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ulica, "Ulica", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ulica, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ulica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KvartId, "Ime kvarta", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KvartId", (SelectList)ViewBag.Kvart, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, "E-mail restorana", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Passw, "Password", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Passw, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Passw, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KucniBroj, "Kućni broj", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KucniBroj, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KucniBroj, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefon, "Telefon", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobitel, "Mobitel", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobitel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobitel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VlasnikId, "OIB vlasnika", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VlasnikId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VlasnikId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi promjene" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak na izbornik uredivanja", "Uredivanje", "Home")
</div>